### ISSUE TITLE
This project is not actually build TypeScript syntax

### ISSUE THREAD

**Issue by getsaf** [splatte/react-native-typescript-babel7-starter#1]
@splatte Maybe you could mark this project as a work-in-progress so others don't burn time referencing this to find that it's not actually using typescript.

Note, the only reason this is compiling is because the `App.tsx` is not using Flow compatible types. As soon as you try to put TypeScript specific code in the file, the compiler blows up.

For example, I tried adding this to `App.tsx`
```typescript
const Foo = { bar: 'baz', fizz: 'buzz' };
const bar: keyof typeof Foo = 'bar'; // <-- TypeScript syntax
console.log(bar);
```

(Note the `bar` variable type is expressed in a TypeScript specific manner)

I get an `Unexpected Token` error on the `const bar` line because the compiler is actually building with Flow syntax.

**Comment by splatte** [comment]
@getsaf True, that was indeed not working as I intended. I changed the preset to use `metro-react-native-babel-preset` and added ts-jest, should be fine now.
